2-alt:
	gcc -Wall -Wextra -Wpedantic -O2 -std=c11 2-alt.c -o 2-alt

2:
	gcc -Wall -Wextra -Wpedantic -O2 -std=c11 2.c -o 2

1:
	ghc 1.hs

1-alt:
	gcc -Wall -Wextra -Wpedantic -O2 -std=c11 1.c -o 1-alt

254:
	gcc -Wall -Wextra -Wpedantic -O2 -std=c11 254.c -o 254

254-dbg:
	gcc -Wall -Wextra -Wpedantic -g -O2 -std=c11 254.c -o 254

clean:
	rm -f 254 1 1.o 1.hi 1-alt 2 2-alt
